server:
  port: 4022
spring:
  cloud:
    gateway:
      routes:
        - id: oss
          uri: lb://chat-club-oss
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=1
          # /oss/getAllBucket
